"""
c25k_utils/qr_export.py
Export a QR code for sharing the C25K plan summary or link.
Fully implements advanced, accessible QR code export.
"""
import os

def export_qr_code(plan, user, outdir):
    try:
        import qrcode
        from qrcode.image.pil import PilImage
    except ImportError:
        print("[Warning] qrcode package not installed. Install with: pip install qrcode[pil]")
        return
    # Build a detailed summary string
    summary = f"C25K for {user['name']} (Start: {user.get('start_day','')})\nGoal: {user.get('goal','')}\nWeeks: {user.get('weeks',10)}\nDays/Week: {user.get('days_per_week',3)}\n"
    summary += "Plan:\n"
    for session in plan:
        if session.get("duration", 0) > 0:
            summary += f"W{session['week']}D{session['day']}: {session['workout']} | {session['tip']}\n"
        else:
            summary += f"W{session['week']}D{session['day']}: Rest Day\n"
    summary += "\nGenerated by C25K Calendar Creator"
    # Optionally, add a link to the project or a shareable file
    if user.get("share_link"):
        summary += f"\nMore: {user['share_link']}"
    # Accessibility: large/high-contrast QR code if selected
    qr_kwargs = {"box_size": 12 if user.get("large_font") else 8, "border": 6 if user.get("high_contrast") else 4}
    qr = qrcode.QRCode(**qr_kwargs)
    qr.add_data(summary)
    qr.make(fit=True)
    img = qr.make_image(fill_color="yellow" if user.get("high_contrast") else "black", back_color="black" if user.get("high_contrast") else "white")
    qr_path = os.path.join(outdir, "C25K_QR_Code.png")
    img.save(qr_path)
    print(f"QR code saved as '{qr_path}' (scan to view plan summary).")
    # Save a Markdown file with the QR code and alt text for accessibility
    md_path = os.path.join(outdir, "C25K_QR_Code.md")
    alt_text = f"QR code for C25K plan for {user['name']} (goal: {user.get('goal','')})"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write("# C25K Plan QR Code\n\n")
        f.write(f"![{alt_text}](C25K_QR_Code.png)\n\n")
        f.write("**Plan summary:**\n\n")
        f.write(f"{summary}\n")
    print(f"Markdown file with QR code and summary saved as '{md_path}'.")
